import 'react-native-gesture-handler';
import 'react-native-reanimated'; // CRITICAL: This MUST be here to prevent the silent crash
import React, { useMemo, useState } from 'react';
import { StatusBar } from 'expo-status-bar';
import {
  Pressable,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { NavigationContainer, DefaultTheme } from '@react-navigation/native';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { LanguageProvider, useLanguage } from './src/context/LanguageContext';
import { AdProvider, ScreenBannerAd } from './src/ads/AdProvider';
import TestRunner from './src/components/TestRunner';
import {
  createPracticeSet,
  getMockTestCatalog,
  getSubjectMasterySnapshot,
  getTeacherSummaryByPaper,
  TestFactory,
} from './src/data/QuestionBank';
import { COLORS, TYPOGRAPHY } from './src/constants/theme';

const Drawer = createDrawerNavigator();
const Stack = createNativeStackNavigator();

const COPY = {
  appTitle: { en: 'MSCE SCHOLARSHIP GUIDE', mr: 'एमएससीई शिष्यवृत्ती मार्गदर्शक' },
  appSubtitle: {
    en: 'Professional bilingual preparation for Std 4th & 7th scholarship exams',
    mr: 'इयत्ता ४ थी व ७ वी शिष्यवृत्ती परीक्षेसाठी व्यावसायिक द्विभाषिक तयारी',
  },
  home: { en: 'Home', mr: 'मुख्यपृष्ठ' },
  mockTests: { en: 'Mock Tests', mr: 'मॉक टेस्ट' },
  practiceChapters: { en: 'Practice Chapters', mr: 'सराव प्रकरणे' },
  dashboard: { en: 'Parent Dashboard', mr: 'पालक डॅशबोर्ड' },
  chooseGrade: { en: 'Choose Grade', mr: 'इयत्ता निवडा' },
  choosePaper: { en: 'Choose Paper', mr: 'पेपर निवडा' },
  std4: { en: 'Std 4th', mr: 'इयत्ता ४ थी' },
  std7: { en: 'Std 7th', mr: 'इयत्ता ७ वी' },
  paper1: { en: 'Paper 1: Marathi + Math', mr: 'पेपर १: मराठी + गणित' },
  paper2: { en: 'Paper 2: English + IQ', mr: 'पेपर २: इंग्रजी + बुद्धिमत्ता' },
  startMock: { en: 'Start Full Mock Test', mr: 'पूर्ण मॉक टेस्ट सुरू करा' },
  startPractice: { en: 'Start Practice Session', mr: 'सराव सत्र सुरू करा' },
  totalBank: { en: 'Question Bank Coverage', mr: 'प्रश्नसंच व्याप' },
  timedPaper: { en: '90-Minute Timed Paper', mr: '९० मिनिटांचा वेळबद्ध पेपर' },
  mastery: { en: 'Subject Mastery', mr: 'विषय प्रभुत्व' },
  weakAlert: { en: 'Weak Topic Alert', mr: 'कमकुवत विषय सूचना' },
  recentTests: { en: 'Recent Tests', mr: 'अलीकडील टेस्ट' },
  summary: { en: "Teacher's Concept Summary", mr: 'शिक्षकांचा संकल्पना सारांश' },
};

function LanguageFab() {
  const { language, toggleLanguage } = useLanguage();

  return (
    <Pressable style={styles.languageFab} onPress={toggleLanguage}>
      <Text style={styles.languageFabText}>{language === 'en' ? 'EN' : 'MR'}</Text>
    </Pressable>
  );
}

function SectionCard({ children, style }) {
  return <View style={[styles.card, style]}>{children}</View>;
}

function ProgressBar({ label, value }) {
  return (
    <View style={styles.progressGroup}>
      <View style={styles.progressHeader}>
        <Text style={styles.progressLabel}>{label}</Text>
        <Text style={styles.progressValue}>{value}%</Text>
      </View>
      <View style={styles.progressTrack}>
        <View style={[styles.progressFill, { width: `${Math.max(0, Math.min(value, 100))}%` }]} />
      </View>
    </View>
  );
}

function HomeScreen() {
  const { t } = useLanguage();
  const catalog = useMemo(() => getMockTestCatalog(), []);

  return (
    <SafeAreaView style={styles.screen}>
      <LanguageFab />
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <SectionCard style={styles.heroCard}>
          <Text style={styles.heroTitle}>{t(COPY.appTitle)}</Text>
          <Text style={styles.heroSubtitle}>{t(COPY.appSubtitle)}</Text>
        </SectionCard>

        <SectionCard>
          <Text style={styles.sectionTitle}>{t(COPY.totalBank)}</Text>
          <Text style={styles.metaText}>{catalog.totalQuestions}+ bilingual questions across Marathi, English, Math and IQ.</Text>
          <Text style={styles.metaText}>{catalog.paper1Tests} Paper 1 mocks and {catalog.paper2Tests} Paper 2 mocks generated by the TestFactory.</Text>
          <Text style={styles.metaText}>{t(COPY.timedPaper)}</Text>
        </SectionCard>
      </ScrollView>
      <View style={styles.bannerDock}>
        <ScreenBannerAd />
      </View>
    </SafeAreaView>
  );
}

function SelectionPanel({ navigation, mode }) {
  const { t } = useLanguage();
  const [grade, setGrade] = useState(4);

  return (
    <>
      <SectionCard>
        <Text style={styles.sectionTitle}>{t(COPY.chooseGrade)}</Text>
        <View style={styles.row}>
          <Pressable
            style={[styles.choiceButton, grade === 4 && styles.choiceButtonActive]}
            onPress={() => setGrade(4)}
          >
            <Text style={[styles.choiceButtonText, grade === 4 && styles.choiceButtonTextActive]}>{t(COPY.std4)}</Text>
          </Pressable>
          <Pressable
            style={[styles.choiceButton, grade === 7 && styles.choiceButtonActive]}
            onPress={() => setGrade(7)}
          >
            <Text style={[styles.choiceButtonText, grade === 7 && styles.choiceButtonTextActive]}>{t(COPY.std7)}</Text>
          </Pressable>
        </View>
      </SectionCard>

      <SectionCard>
        <Text style={styles.sectionTitle}>{t(COPY.choosePaper)}</Text>
        <Pressable
          style={styles.primaryButton}
          onPress={() => navigation.navigate('Session', { grade, paper: 'paper1', mode })}
        >
          <Text style={styles.primaryButtonText}>
            {mode === 'mock' ? t(COPY.startMock) : t(COPY.startPractice)} • {t(COPY.paper1)}
          </Text>
        </Pressable>
        <Pressable
          style={styles.primaryButton}
          onPress={() => navigation.navigate('Session', { grade, paper: 'paper2', mode })}
        >
          <Text style={styles.primaryButtonText}>
            {mode === 'mock' ? t(COPY.startMock) : t(COPY.startPractice)} • {t(COPY.paper2)}
          </Text>
        </Pressable>
      </SectionCard>
    </>
  );
}

function TestSelectionScreen({ navigation, mode }) {
  return (
    <SafeAreaView style={styles.screen}>
      <LanguageFab />
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <SelectionPanel navigation={navigation} mode={mode} />
      </ScrollView>
      <View style={styles.bannerDock}>
        <ScreenBannerAd />
      </View>
    </SafeAreaView>
  );
}

function MockTestsScreen({ navigation }) {
  return <TestSelectionScreen navigation={navigation} mode="mock" />;
}

function PracticeChaptersScreen({ navigation }) {
  const { t, language } = useLanguage();
  const teacherSummary = getTeacherSummaryByPaper('paper1', language);

  return (
    <SafeAreaView style={styles.screen}>
      <LanguageFab />
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <SectionCard>
          <Text style={styles.sectionTitle}>{t(COPY.summary)}</Text>
          <Text style={styles.summaryTitle}>{teacherSummary.title}</Text>
          {teacherSummary.bullets.map((bullet) => (
            <Text key={bullet} style={styles.bulletText}>
              • {bullet}
            </Text>
          ))}
        </SectionCard>

        <SelectionPanel navigation={navigation} mode="practice" />
      </ScrollView>
      <View style={styles.bannerDock}>
        <ScreenBannerAd />
      </View>
    </SafeAreaView>
  );
}

function DashboardScreen() {
  const { t } = useLanguage();
  const [mastery, setMastery] = useState(getSubjectMasterySnapshot());

  React.useEffect(() => {
    AsyncStorage.getItem('msce_scholarship_guide_parent_analytics_v1').then((raw) => {
      const records = JSON.parse(raw ?? '[]');
      if (!records.length) {
        return;
      }

      const average = (key) =>
        Math.round(records.reduce((sum, item) => sum + (item[key] ?? 0), 0) / records.length);

      setMastery({
        mathematics: average('mathematics'),
        intelligence: average('intelligence'),
        marathi: average('marathi'),
        english: average('english'),
        weakTopic: records[records.length - 1]?.weakTopic ?? 'N/A',
        recentTests: records
          .slice(-10)
          .reverse()
          .map((item) => ({
            id: item.id,
            date: new Date(item.completedAt).toLocaleDateString('en-GB'),
            score: `${item.score}/${item.total}`,
            timeTaken: `${item.timeSpentMinutes}m`,
          })),
      });
    });
  }, []);

  return (
    <SafeAreaView style={styles.screen}>
      <LanguageFab />
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <SectionCard>
          <Text style={styles.sectionTitle}>{t(COPY.mastery)}</Text>
          <ProgressBar label="Mathematics" value={mastery.mathematics} />
          <ProgressBar label="Intelligence" value={mastery.intelligence} />
          <ProgressBar label="Marathi" value={mastery.marathi} />
          <ProgressBar label="English" value={mastery.english} />
        </SectionCard>

        <SectionCard>
          <Text style={styles.sectionTitle}>{t(COPY.weakAlert)}</Text>
          <Text style={styles.metaText}>{mastery.weakTopic}</Text>
        </SectionCard>

        <SectionCard>
          <Text style={styles.sectionTitle}>{t(COPY.recentTests)}</Text>
          {mastery.recentTests.map((item) => (
            <View key={item.id} style={styles.tableRow}>
              <Text style={styles.tableCell}>{item.date}</Text>
              <Text style={styles.tableCell}>{item.score}</Text>
              <Text style={styles.tableCell}>{item.timeTaken}</Text>
            </View>
          ))}
        </SectionCard>
      </ScrollView>
      <View style={styles.bannerDock}>
        <ScreenBannerAd />
      </View>
    </SafeAreaView>
  );
}

function SessionScreen({ route, navigation }) {
  const { grade, paper, mode } = route.params;
  const test = useMemo(() => {
    return mode === 'mock'
      ? TestFactory.createMockTest({ grade, paper })
      : createPracticeSet({ grade, paper });
  }, [grade, paper, mode]);

  return (
    <TestRunner
      test={test}
      mode={mode}
      onSubmit={(result) => navigation.replace('Result', { result })}
    />
  );
}

function ResultScreen({ route, navigation }) {
  const { result } = route.params;

  return (
    <SafeAreaView style={styles.screen}>
      <LanguageFab />
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <SectionCard>
          <Text style={styles.sectionTitle}>Result Summary</Text>
          <Text style={styles.scoreText}>
            {result.score} / {result.questions.length}
          </Text>
          {Object.entries(result.subjectBreakdown).map(([subject, value]) => (
            <View key={subject} style={styles.tableRow}>
              <Text style={styles.tableCell}>{subject.toUpperCase()}</Text>
              <Text style={styles.tableCell}>
                {value.correct}/{value.total}
              </Text>
            </View>
          ))}
        </SectionCard>

        <Pressable style={styles.primaryButton} onPress={() => navigation.popToTop()}>
          <Text style={styles.primaryButtonText}>Back to Home</Text>
        </Pressable>
      </ScrollView>
      <View style={styles.bannerDock}>
        <ScreenBannerAd />
      </View>
    </SafeAreaView>
  );
}

function DrawerShell() {
  const { t } = useLanguage();

  return (
    <Drawer.Navigator
      screenOptions={{
        headerStyle: { backgroundColor: COLORS.blue },
        headerTintColor: '#FFFFFF',
        drawerActiveTintColor: COLORS.blue,
        drawerInactiveTintColor: COLORS.text,
        drawerLabelStyle: { fontSize: 15, fontWeight: '600' },
      }}
    >
      <Drawer.Screen name="Home" component={HomeScreen} options={{ title: t(COPY.home) }} />
      <Drawer.Screen name="MockTests" component={MockTestsScreen} options={{ title: t(COPY.mockTests) }} />
      <Drawer.Screen name="PracticeChapters" component={PracticeChaptersScreen} options={{ title: t(COPY.practiceChapters) }} />
      <Drawer.Screen name="ParentDashboard" component={DashboardScreen} options={{ title: t(COPY.dashboard) }} />
    </Drawer.Navigator>
  );
}

function AppNavigator() {
  const navTheme = {
    ...DefaultTheme,
    colors: {
      ...DefaultTheme.colors,
      background: '#FFFFFF',
      card: '#FFFFFF',
      border: '#D8E0EA',
      text: COLORS.text,
      primary: COLORS.blue,
    },
  };

  return (
    <NavigationContainer theme={navTheme}>
      <Stack.Navigator
        screenOptions={{
          headerStyle: { backgroundColor: COLORS.blue },
          headerTintColor: '#FFFFFF',
          headerTitleStyle: { fontWeight: '700' },
          contentStyle: { backgroundColor: '#FFFFFF' },
        }}
      >
        <Stack.Screen name="Root" component={DrawerShell} options={{ headerShown: false }} />
        <Stack.Screen name="Session" component={SessionScreen} options={{ title: 'Practice Session' }} />
        <Stack.Screen name="Result" component={ResultScreen} options={{ title: 'Result' }} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default function App() {
  return (
    <SafeAreaProvider>
      <LanguageProvider>
        <AdProvider>
          <StatusBar style="light" />
          <AppNavigator />
        </AdProvider>
      </LanguageProvider>
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 110,
    gap: 16,
  },
  heroCard: {
    backgroundColor: '#F6FAFF',
    borderColor: '#CFE0F7',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D8E0EA',
    borderRadius: 18,
    padding: 16,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: COLORS.blue,
  },
  heroSubtitle: {
    fontSize: 15,
    lineHeight: 22,
    color: COLORS.muted,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.heading,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 12,
  },
  metaText: {
    fontSize: 15,
    lineHeight: 22,
    color: COLORS.muted,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    gap: 12,
  },
  choiceButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D8E0EA',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  choiceButtonActive: {
    borderColor: COLORS.blue,
    backgroundColor: '#EEF5FF',
  },
  choiceButtonText: {
    color: COLORS.text,
    fontWeight: '700',
  },
  choiceButtonTextActive: {
    color: COLORS.blue,
  },
  primaryButton: {
    backgroundColor: COLORS.blue,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 15,
    textAlign: 'center',
  },
  summaryTitle: {
    color: COLORS.blue,
    fontWeight: '800',
    marginBottom: 8,
  },
  bulletText: {
    color: COLORS.text,
    lineHeight: 22,
    marginBottom: 4,
  },
  progressGroup: {
    marginBottom: 14,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  progressLabel: {
    color: COLORS.text,
    fontWeight: '700',
  },
  progressValue: {
    color: COLORS.blue,
    fontWeight: '800',
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#E9EFF6',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: COLORS.blue,
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
  },
  tableCell: {
    color: COLORS.text,
    fontWeight: '600',
    flex: 1,
  },
  scoreText: {
    fontSize: 30,
    fontWeight: '800',
    color: COLORS.blue,
    marginBottom: 14,
  },
  bannerDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 6,
    alignItems: 'center',
  },
  languageFab: {
    position: 'absolute',
    right: 16,
    bottom: 90,
    zIndex: 50,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.blue,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#001B44',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  languageFabText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 14,
  },
});
